pipelines:
  GrilloApp:
    group: Playa
    materials:
      repo:
        branch: master
        git: "https://github.com/TW-Playa-Chile/AppPlaya"
    stages:
       - pruebas:
          jobs:
            pruebas_unitarias:
              resources:
                - node-agent
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
                - exec:
                    command: jest
                        
