pipelines:
  GrilloApp:
    group: Playa
    materials:
      repo:
        branch: master
        git: "https://github.com/TW-Playa-Chile/AppPlaya"
    stages:
       - test:
          jobs:
            unit_test:
              resources:
                - node-agent
              tasks:
                - exec:
                    command: npm
                    arguments:
                      - install
