pipelines: 
  GrilloApp: 
    group: Playa
    materials: 
      repo: 
        branch: master
        git: "https://github.com/TW-Playa-Chile/AppPlaya"
    stages: 
      - 
        pruebas: 
          jobs:
            timeout: 60
            pruebas_unitarias: 
              resources: 
                - node-agent
              tasks: 
                - exec: 
                    command: npm test
